version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
      # Core settings
      WEBSOCKET_ENABLED: "true"
      DOMAIN: "${DOMAIN:-http://localhost:8088}"
      
      # Security settings
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      SIGNUPS_ALLOWED: "${SIGNUPS_ALLOWED:-false}"
      INVITATIONS_ALLOWED: "${INVITATIONS_ALLOWED:-true}"
      SHOW_PASSWORD_HINT: "${SHOW_PASSWORD_HINT:-false}"
      
      # Performance settings
      DATABASE_MAX_CONNS: "${DATABASE_MAX_CONNS:-10}"
      WEB_VAULT_ENABLED: "${WEB_VAULT_ENABLED:-true}"
      
      # Email settings (optional)
      SMTP_HOST: "${SMTP_HOST:-}"
      SMTP_FROM: "${SMTP_FROM:-}"
      SMTP_PORT: "${SMTP_PORT:-587}"
      SMTP_SECURITY: "${SMTP_SECURITY:-starttls}"
      SMTP_USERNAME: "${SMTP_USERNAME:-}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:-}"
      
      # Logging
      LOG_LEVEL: "${LOG_LEVEL:-warn}"
      EXTENDED_LOGGING: "${EXTENDED_LOGGING:-true}"
      
      # Rate limiting
      LOGIN_RATELIMIT_SECONDS: "${LOGIN_RATELIMIT_SECONDS:-60}"
      LOGIN_RATELIMIT_MAX_BURST: "${LOGIN_RATELIMIT_MAX_BURST:-10}"
      
      # File size limits
      ATTACHMENT_LIMIT: "${ATTACHMENT_LIMIT:-10240}"
      SEND_LIMIT: "${SEND_LIMIT:-1048576}"
    volumes:
      - vaultwarden_data:/data
    ports:
      - "${VAULTWARDEN_PORT:-8088}:80"
      - "${WEBSOCKET_PORT:-3012}:3012"
    networks:
      - vaultwarden_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "backup.enable=true"

  backup:
    image: ghcr.io/johannmx/vaultwarden_backup:main
    container_name: vaultwarden_backup
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    network_mode: none
    volumes:
      - vaultwarden_data:/data:ro
      - backup_data:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Backup settings
      DELETE_AFTER: "${BACKUP_DELETE_AFTER:-30}"
      CRON_TIME: "${BACKUP_CRON_TIME:-0 2 * * *}"  # Daily at 2 AM
      UID: "${BACKUP_UID:-1000}"
      GID: "${BACKUP_GID:-1000}"
      TZ: "${TZ:-America/Argentina/Buenos_Aires}"
      
      # Notification settings
      GOTIFY_TOKEN: "${GOTIFY_TOKEN:-}"
      GOTIFY_SERVER: "${GOTIFY_SERVER:-}"
      SLACK_WEBHOOK: "${SLACK_WEBHOOK:-}"
      DISCORD_WEBHOOK_ID: "${DISCORD_WEBHOOK_ID:-}"
      DISCORD_WEBHOOK_TOKEN: "${DISCORD_WEBHOOK_TOKEN:-}"
    depends_on:
      vaultwarden:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Optional: Watchtower for automatic updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: vaultwarden_watchtower
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "86400"  # Check daily
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      WATCHTOWER_NOTIFICATIONS: "gotify"
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: "${GOTIFY_SERVER:-}"
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: "${GOTIFY_TOKEN:-}"
    profiles:
      - watchtower  # Enable with: docker-compose --profile watchtower up

volumes:
  vaultwarden_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${VAULTWARDEN_DATA_PATH:-./data}"
  backup_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${BACKUP_DATA_PATH:-./backups}"

networks:
  vaultwarden_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: vw-bridge